---
- name: Create docker volumes directory
  file:
    path: /var/lib/docker/volumes
    state: directory
    owner: root
    group: root
    mode: 0700

- name: Partition disk
  parted:
    device: /dev/sdb
    number: 1
    state: present

- name: Create a ext4 filesystem on /dev/sdb1 and check disk blocks
  filesystem:
    fstype: ext4
    dev: /dev/sdb1

- name: Mount docker disk
  mount:
    path: /var/lib/docker/volumes
    src: /dev/sdb1
    fstype: ext4
    state: mounted
