---
- name: ensure wget is available
  apt:
    name: wget
    state: present
    update_cache: true

- name: ensure gtar is available
  apt:
    name: tar
    state: present


- name: ensure jq is available
  apt:
    name: jq
    state: present

- name: check if node exporter already exists
  stat:
    path: /var/node_exporter/node_exporter/node_exporter
  register: node_e

- name: create node exporter dir
  file:
    path: /var/node_exporter
    state: directory
    owner: root
    group: root
    mode: 0744
  when: not node_e.stat.exists

- name: download node exporter
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v0.16.0/node_exporter-0.16.0.linux-amd64.tar.gz
    dest: /var/node_exporter
  when: not node_e.stat.exists

- name: extract node exporter
  unarchive:
    remote_src: yes
    src: /var/node_exporter/node_exporter-0.16.0.linux-amd64.tar.gz
    dest: /var/node_exporter
  when: not node_e.stat.exists

- name: check if node exporter is running
  wait_for:
    port: 9100
    timeout: 2
    delay: no
  register: node_c
  ignore_errors: true

- name: create node_exporter/data directory
  command: mkdir -p /var/prom_exports/data

- name: copy over block height check
  copy:
    src: block_height.sh
    dest: /var/prom_exports/block_height.sh
    owner: root
    group: root
    mode: 0755

- name: cron for exporter
  cron:
    name: "check block height"
    minute: "*/10"
    job: "/var/prom_exports/block_height.sh"

- name: if port is not in use then start node exporter
  shell: cd /var/node_exporter/node_exporter-0.16.0.linux-amd64; nohup ./node_exporter --collector.textfile.directory=/var/prom_exports/data >/dev/null 2>&1 &
  when: node_c.failed

- name: check if node exporter is running
  wait_for:
    port: 9100
    timeout: 2
    delay: no
  register: node_d
  ignore_errors: true

- name: debug node_d
  debug: var=node_d
