---
- name: Make apt-transport-https present
  apt:
    name: apt-transport-https
    state: present
    update_cache: true

- name: Make ca-certificates present
  apt:
    name: ca-certificates
    state: present
    update_cache: true

- name: Make curl present
  apt:
    name: curl
    state: present
    update_cache: true

- name: Make software-properties-common present
  apt:
    name: software-properties-common
    state: present
    update_cache: true

- name: Add docker apt signing key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add apt repo
  apt_repository:
    repo:  "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
    state: present

- name: Install docker ce
  apt:
    name: docker-ce
    state: present
    update_cache: true

- name: Add user to docker group
  user:
    append: yes
    name: ubuntu
    groups: docker

- name: Add docker compose if needed
  apt:
    name: docker-compose
  when: docker_compose

- name: Make docker TLS dir
  file:
    path: /etc/ssl/docker
    state: directory
    owner: root
    group: root
    mode: 0744
  when: docker_tls

- name: Add tls cert
  copy:
    src: cert.pem
    dest: /etc/ssl/docker/cert.pem
    owner: root
    group: root
    mode: 0600
  when: docker_tls

- name: Add tls key
  copy:
    src: key.pem
    dest: /etc/ssl/docker/key.pem
    owner: root
    group: root
    mode: 0600
  when: docker_tls

- name: Add docker daemon.json
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    mode: 0644
  when: docker_tls
  notify: restart docker
