---
- name: factom monitoring server
  hosts: all
  become: yes

  gather_facts: false

  pre_tasks:
    - name: Install python for Ansible
      become: true
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      changed_when: false
    - setup:

  roles:
    - { role: docker, tags: [ docker ], docker_compose: true }
    - { role: prometheus, tags: [ prometheus ] }
